name: 'Setup clj-kondo'
description: 'Provision hosted runner with clj-kondo'
author: 'DeLaGuardo'
branding:
  icon: 'gift'
  color: 'blue'
inputs:
  version:
    description: 'desired version of clj-kondo to install'
runs:
  using: 'node12'
  main: 'lib/main.js'
