name: "Test setup-clj-kondo"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - uses: ./
      with:
        version: 2019.11.23
        path-to-lint: src
    - run: echo '(def x 1)' | clj-kondo --lint -
